global: 
  scrape_interval: 15s  # Scrape metrics every 15 seconds

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['<server_ip>:8001']  # Replace with your server's IP address
