global:
  scrape_interval: 15s  # Scrape metrics every 15 seconds

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8001']  # Using the Docker service name 'backend'
