name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./solar_ui

      - name: Run ESLint
        run: npm run lint --fix
        working-directory: ./solar_ui

      - name: Run Prettier
        run: npx prettier --write .
        working-directory: ./solar_ui

      - name: Build Project
        env:
          CI: false # Disabling the CI environment variable to prevent treating warnings as errors
        run: npm run build
        working-directory: ./solar_ui
